### ISSUE TITLE
Remove leading and trailing quotes from results

### ISSUE THREAD

**Issue by drasive** [damkraw/grunt-gitinfo#20]
Some of the commands return a response with added leading and a trailing quotes, event though the original result didn't contain them:
![output](https://cloud.githubusercontent.com/assets/8427113/4881814/a9ca4cd0-634d-11e4-8089-c0b0e1039717.png)

It would be nice to have the results without the additional quotes.

**Comment by damkraw** [comment]
This issue doesn't happen on my test envs (mac os, linux). Closing as can not reproduce.
