### ISSUE TITLE
git object remains empty

### ISSUE THREAD

**Issue by sgagovic** [damkraw/grunt-gitinfo#26]
I want to create grunt task that is going to write git information to file. However, I am not getting any git information. I followed instructions but cannot figure out what I am doing wrong. Inside my grunt file I have following:

grunt.loadNpmTasks('grunt-gitinfo');

grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        gitinfo: {},
       ....
})

....
grunt.registerTask('gitVersion', [
        'gitinfo'
    ]);

grunt.registerTask('version', 'Creates an empty file', function() {
        var git = grunt.config().gitinfo;
        var pjson = require('./package.json');

        console.log(pjson.version);

        grunt.file.write('VERSION.txt', "Version: " + pjson.version + "\r\n" + git);
});

After running the task new file is created and psjon.version is written but git object remains empty.

**Comment by damkraw** [comment]
That is because you did not run `gitinfo` task before accessing it. Below should work:

    module.exports = function (grunt) {
        grunt.loadNpmTasks('grunt-gitinfo');

        grunt.initConfig({
            pkg: grunt.file.readJSON('package.json'),
            gitinfo: {},
        });
        grunt.registerTask('yourWriteFunction', 'Write', function () {
            var git = grunt.config('gitinfo');
            console.log(git);
        });

        grunt.registerTask('version', 'qeues tasks', function() {
            //Run gitinfo task
            grunt.task.run('gitinfo');

            //Run your write function
            grunt.task.run('yourWriteFunction');
        });
    }

**Comment by SiamKreative** [comment]
Hi @damkraw,

I have an issue with my Gruntfile and I hope you could help me figure it out.

`Warning: An error occurred while processing a template (Cannot read property 'branch' of undefined). Use --force to continue.`

![image](https://cloud.githubusercontent.com/assets/1778633/13067490/1d025446-d4a3-11e5-9daa-0fddb9abad92.png)

I'd be grateful if you could take a look at my [Gruntfile.js](https://gist.github.com/SiamKreative/480029f278d35cbacdad)

Thanks

**Comment by SiamKreative** [comment]
Forget about it, I fixed it by adding the `gitinfo` as the first task in my build task.
